### ISSUE TITLE
Must need an update

### ISSUE THREAD

**Issue by th3gh0s8** [SLRAPTOR/GYM_Project#6]
This project is outdated

**Comment by SLRAPTOR** [comment]
What do you suggest

**Comment by SLRAPTOR** [comment]
> This project is outdated

What do you suggest

**Comment by th3gh0s8** [comment]
> > This project is outdated
> 
> What do you suggest

We can update it using Ruby on Rails

**Comment by SLRAPTOR** [comment]
> > > This project is outdated
> > 
> > 
> > What do you suggest
> 
> We can update it using Ruby on Rails

ok

**Comment by th3gh0s8** [comment]
> > > > This project is outdated
> > > 
> > > 
> > > What do you suggest
> > 
> > 
> > We can update it using Ruby on Rails
> 
> ok

Ok then ill implement that
